FROM fusuf/whatsasena:latest

RUN git clone https://Sew01RaviduManoj01KingAndQueen:sew01ravindumanoj10kingandqueen@github.com/Sew01RaviduManoj01KingAndQueen/Sew01Ravindu10KingAndQueen /root/QueenSew
WORKDIR /root/QueenSew/
ENV TZ=Europe/Istanbul
RUN npm install supervisor -g
RUN yarn install --no-audit

CMD ["node", "bot.js"]
